### ISSUE TITLE
CodeEditorField::setHeight() has no effect

### ISSUE THREAD

**Issue by lozcalver** [jinjie/codeeditorfield#3]
https://github.com/jinjie/codeeditorfield/blob/master/src/Forms/CodeEditorField.php#L25-L31

Also, scalar type hints are PHP 7 only - I’d suggest either removing the hint or updating `composer.json` to require PHP 7 (plus add `silverstripe/framework`!) :)

**Comment by jinjie** [comment]
@kinglozzer Thank you for the heads up! 😄
