### ISSUE TITLE
Type hint for CodeEditorField::setMode() is wrong

### ISSUE THREAD

**Issue by lozcalver** [jinjie/codeeditorfield#4]
Should be `string`: https://github.com/jinjie/codeeditorfield/blob/master/src/Forms/CodeEditorField.php#L60

**Comment by jinjie** [comment]
@kinglozzer Should it be? It returns $this, which is an instance of `CodeEditorField`.

**Comment by lozcalver** [comment]
Yep, it’s the `@param` that’s wrong though, not `@return` 😁

**Comment by jinjie** [comment]
Now I know what you mean. Fixed! 🙇
